In [5]:
import numpy as np
import matplotlib.pylab as plt
from numba import njit
import plotly.graph_objects as go

3. **Diagonalización**.

Se sabe que un sistema físico es gobernado por las ecuaciones,



$$
\begin{matrix}
x' &=& 2x&-y&+z, \\
y' &=&   &3y&-1z, \\
z' &=& 2x&+y&+3z,
\end{matrix}
$$

donde $x',y',z'$ son las derivadas, en forma vectorial esto se puede representar como $\mathbf{r}'=A\mathbf{r}$ que tiene solución analítica general, $\mathbf{r} = e^{At} \mathbf{r}(0)$.<br>
a) Diagonalize $A$.<br>

In [ ]:
A = np.array([[2, -1, 1], [0, 3, -1], [2, 1, 3]])
eigvals, eigvecs = np.linalg.eig(A) 
D = np.diag(eigvals) #matrix de valores propios
P = eigvecs          #matriz de vectores propios
A_reconstructed = np.array( P @ D @ np.linalg.inv(P))

print("Matriz A:")
print(A)
print("\nValores propios:")
print(eigvals)
print("\nMatriz de vectores propios P:")
print(P)
print("\nMatriz diagonal D:")
print(D)
print("\nVerificación A = P D P^-1:")
print(A_reconstructed)

Matriz A:
[[ 2 -1  1]
 [ 0  3 -1]
 [ 2  1  3]]

Valores propios:
[4.+0.00000000e+00j 2.+1.68652966e-08j 2.-1.68652966e-08j]

Matriz de vectores propios P:
[[-0.57735027+0.00000000e+00j -0.57735027+9.73718355e-09j
  -0.57735027-9.73718355e-09j]
 [ 0.57735027+0.00000000e+00j  0.57735027+0.00000000e+00j
   0.57735027-0.00000000e+00j]
 [-0.57735027+0.00000000e+00j  0.57735027-9.73718355e-09j
   0.57735027+9.73718355e-09j]]

Matriz diagonal D:
[[4.+0.00000000e+00j 0.+0.00000000e+00j 0.+0.00000000e+00j]
 [0.+0.00000000e+00j 2.+1.68652966e-08j 0.+0.00000000e+00j]
 [0.+0.00000000e+00j 0.+0.00000000e+00j 2.-1.68652966e-08j]]

Verificación A = P D P^-1:
[[ 2.00000000e+00+4.22907063e-10j -1.00000000e+00+4.22907063e-10j
   1.00000000e+00-2.16182500e-24j]
 [ 1.88737914e-15-4.45946263e-10j  3.00000000e+00-4.45946263e-10j
  -1.00000000e+00-1.79300708e-24j]
 [ 2.00000000e+00+2.91325159e-11j  1.00000000e+00+2.91325159e-11j
   3.00000000e+00+1.30125162e-24j]]


# Actividad:

1. Construir un programa que permita multiplicar dos matrices

2. Cosntruir un programa que permita construir una regresion lineal simple empleando lo que sigue:

3. Construir un programa que permita calcular una regresion bidimensional y hacer su representación .


Operaciones matricial con regresión lineal.

Cuando se desea hacer una regresion lineal multivariada, existen diferentes formas de realizar la regresión, una de ellas es encontrar el error cuadrático medio y miniminzar el conjunto de parámetros de la regresión emplando algún metodo de minimización, otra forma es encontrar la expresión analítica en forma matricial para enoncontrar el conjunto de parametros de la regresión. En este último caso, la regresion lineal viene dada por la siguiente expresion generalizada:


- $\Theta = (X^T X)^{-1} X^T y$

donte $\Theta$ es la matriz de parametros asociados a la regresión lineal, X la matriz de características y y los valos esperados, así, si tenemos una conjunto de datos en N dimensiones la recta, plano o hyperplano puede ser calculado como:

$Y=\Theta^T X$


En el caso de dos dimensiones, tenemos lo siguiente, Supongamos que X, y Y presentan un comportamiento lineal, y vienen dados por:


- Sea $\vec{X}=x^1, x^2, x^3, x^4, ..., x^m$
- Sea $\vec{Y}=y^1, y^2, y^3, y^4, ..., y^m$

Para determinar la ecuacion de la recta, hay que conocer los párametros $\theta_0 $, $\theta_1$, que cumplen que :   $y^{i} = \theta_1 x^{i} + \theta_0$ la anterior expresion puede ser escrita como:

\begin{equation}
\begin{bmatrix}
y^{1}\\
y^{2}\\
\vdots\\
y^{m}\\
\end{bmatrix}=
\begin{bmatrix}
\theta_0 & \theta_1 \\
\end{bmatrix}
\begin{bmatrix}
1 & 1 & \cdots & 1 \\
x_1^{1} & x_1^{2} & \cdots & x_1^{m} \\
\end{bmatrix}
\end{equation}


Para determinar la matriz de theta entonces se puede aplicar la ecuación:

- $\Theta = (X^T X)^{-1} X^T y$

donde:
\begin{equation}
X=
\begin{bmatrix}
1 & x_1^{1} \\
1 & x_1^{2} \\
\vdots & \vdots \\
1 & x_1^{m}
\end{bmatrix}
\end{equation}

y


\begin{equation}
y=
\begin{bmatrix}
y^1 \\
y^2 \\
\vdots\\
y^m
\end{bmatrix}
\end{equation}

Su tarea será construir un programa que realice la regresión lineal para los siguientes puntos:
```python
N = 10
x1 = np.linspace(0, 10, N)
noise=2*np.random.random(N)-1
y = 0.9*x1 + noise
```



Generalice para el siguiente problema bidimensional:


```python
N = 10
x1 = np.linspace(-1, 1, N)
x2 = np.linspace(-2, 2, N)
noise1=2*np.random.random(N)-1
noise2=2*np.random.random(N)-1
y = 2*(x1+noise1) - 3*(x2+noise2) + 0.0 #+ 4*np.random.random(100)

N = 10
X1, X2 = np.meshgrid(x1,x2)
Y = 2*X1 - 3*X2 + 0.0
fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
surf = ax.plot_surface(X1, X2, Y)
#scatter = ax.scatter(x1, x2, y,"-")
```



4. Construir un programa que permita realizar eliminacion de Gauss- Jordan de una matriz

In [ ]:
@njit
def punto(a,b):
  c=0
  for i in range(0,len(a)):
    c = c + a[i] * b[i]

  return c

@njit
def multi(a,b):
  b= np.transpose(b)
  C = np.zeros((len(a),len(b)))

  for i in range(len(a)):
    for j in range(len(b)):

      C[i][j] = punto(a[i],b[i])
  return C

#funciones sin njit
def punto2(a,b):
  c=0
  for i in range(0,len(a)):
    c = c + a[i] * b[i]

  return c

def multi2(a,b):
  b = np.transpose(b)
  C = np.zeros((len(a),len(b)))

  for i in range(len(a)):
    for j in range(len(b)):

      C[i][j] = punto2(a[i],b[i])
  return C

In [9]:
n = 100
a = np.random.randint(10, size=(n, n))
b = np.random.randint(10, size=(n, n))

A= np.matrix(a)
B= np.matrix(b)

print("multiplicacion ordinaria")
%timeit A@B
print()
print("multiplicacion numba")
%timeit multi(a,b)
print()
print("multiplicacion sin numba")
%timeit multi2(a,b)

multiplicacion ordinaria
767 μs ± 107 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

multiplicacion numba
393 μs ± 5.55 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

multiplicacion sin numba
165 ms ± 4.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


regresion lineal:

In [ ]:
N = 10
x1 = np.linspace(-1, 1, N)
x2 = np.linspace(-2, 2, N)
noise1=2*np.random.random(N)-1
noise2=2*np.random.random(N)-1
y = 2*(x1+noise1) - 3*(x2+noise2) + 0.0 

N = 10
X1, X2 = np.meshgrid(x1,x2)
x1_points = np.random.uniform(-1, 1, N)
x2_points = np.random.uniform(-2, 2, N)
y_points = 2 * x1_points - 3 * x2_points + noise1  # Agregar ruido
Y = 2*X1 - 3*X2 + 0.0


# ** Plotly 3D Surface Plot con puntos **
fig = go.Figure()

# Agregar el plano
fig.add_trace(go.Surface(z=Y, x=X1, y=X2, colorscale="viridis", opacity=0.7))

# Agregar puntos
fig.add_trace(go.Scatter3d(x=x1_points, y=x2_points, z=y_points, 
                           mode='markers', marker=dict(color='red', size=5),
                           name="Datos"))

# Configurar diseño
fig.update_layout(title='Plano + Puntos en 3D',
                  scene=dict(xaxis_title='X1',
                             yaxis_title='X2',
                             zaxis_title='Y'),
                  margin=dict(l=0, r=0, b=0, t=40))

fig.show()